
format = "terminal"
color_mode = "custom"

ascii = true
logo_position = "right"
logo_justify = "bottom"
footer_align = "full"

[colors]
border = "#6e6a86"
background = ""
header = "#e0def4"
value = "#e0def4"
sitch = "#c4a7e7"

[colors.titles]
os = "#eb6f92"
host = "#f6c177"
disk = "#eb6f92"
memory = "#9ccfd8"
kernel = "#3e8fb0"
uptime = "#c4a7e7"
gpu = "#31748f"
igpu = "#9ccfd8"
cpu = "#f6c177"
packages = "#e0def4"
shell = "#f6c177"
display = "#9ccfd8"
desktop = "#c4a7e7"
terminal = "#eb6f92"
os-age = "#eb6f92"
locale = "#c4a7e7"
logo = "#bb9af7"
