package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// logoFile is one source art file plus its derived Go map key.
type logoFile struct {
	key   string
	raw   string
	lines int
}

// run generates logos.go from the fastfetch source art in inDir.
func run(inDir, outFile string) error {
	entries, err := os.ReadDir(inDir)
	if err != nil {
		return fmt.Errorf("read logo directory: %w", err)
	}

	logos := make([]logoFile, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".txt") {
			continue
		}
		key := strings.TrimSuffix(e.Name(), ".txt")
		data, err := os.ReadFile(filepath.Join(inDir, e.Name()))
		if err != nil {
			return fmt.Errorf("read logo %s: %w", e.Name(), err)
		}
		text := strings.TrimRight(string(data), "\n")
		logos = append(logos, logoFile{key: key, raw: text, lines: strings.Count(text, "\n") + 1})
	}
	slices.SortFunc(logos, func(a, b logoFile) int { return strings.Compare(a.key, b.key) })

	if err := writeLogos(outFile, logos); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "Generated %d logos\n", len(logos))
	return nil
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: gen_logos <input-dir> <output-file>")
		os.Exit(1)
	}
	if err := run(os.Args[1], os.Args[2]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// writeLogos emits the generated Go source for logos.
func writeLogos(outFile string, logos []logoFile) error {
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("create output file: %w", err)
	}
	w := bufio.NewWriter(f)
	write := func(format string, args ...any) error {
		if _, err := fmt.Fprintf(w, format, args...); err != nil {
			return fmt.Errorf("write generated source: %w", err)
		}
		return nil
	}
	lines := []string{
		"// Code generated by gen_logos.go. DO NOT EDIT.",
		"//",
		"//go:generate go run ./cmd/gen_logos ./internal/render/logos_fastfetch ./internal/render/logos.go",
		"// Source: fastfetch ascii art (https://github.com/fastfetch-cli/fastfetch)",
		"//",
		"// $1..$9 placeholders in the source art are replaced at render time with",
		"// the configured titleColors palette (cycled if more than 9 lines).",
		"",
		"package render",
		"",
		"// fastfetchLogo is one distro's ASCII art with placeholder colors.",
		"type fastfetchLogo struct {",
		"\ttext  string",
		"\tlines int",
		"}",
		"",
		"// fastfetchLogos maps distro id (lowercased) to its ASCII art.",
		"var fastfetchLogos = map[string]fastfetchLogo{",
	}
	for _, line := range lines {
		if err := write("%s\n", line); err != nil {
			_ = f.Close()
			return err
		}
	}
	for _, l := range logos {
		if err := write("\t%q: {text: %s, lines: %d},\n", l.key, escapeGoString(l.raw), l.lines); err != nil {
			_ = f.Close()
			return err
		}
	}
	if err := write("%s\n%s\n", "}", "// defaultLogoText is the fallback art for unknown distros."); err != nil {
		_ = f.Close()
		return err
	}
	if err := write("%s\n", "var defaultLogoText = `"); err != nil {
		_ = f.Close()
		return err
	}
	for _, line := range []string{
		"       .:++",
		"      :+%%%%:",
		"     .+%%%%%%:",
		"    :%%.+ %%%%%",
		"   +%%.  %%%%%%%",
		"  +%%%:+ %%%%%%%:",
		"  +%%%%%%:.%%%%%%",
		"   %%%%%%%.%%%%%",
		"    %%%%%%%.%%%%",
		"     %%%%%%%.%%",
		"      %%%%%%%.",
		"       %%%%%%",
		"        .:-.",
		"`",
	} {
		if err := write("%s\n", line); err != nil {
			_ = f.Close()
			return err
		}
	}
	if err := w.Flush(); err != nil {
		_ = f.Close()
		return fmt.Errorf("flush generated source: %w", err)
	}
	return f.Close()
}

func escapeGoString(s string) string {
	// Escape for double-quoted Go string literal.
	// We emit a "double-quoted" Go string, so we only need to escape
	// backslash and double-quote (and control chars if any). We want the
	// real characters \n \r \t to round-trip as the actual characters, not
	// as literal backslash sequences.
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
